  };

  const changeQty = (id, amount) => {
    setCart((current) => current.map((item) => item.id === id ? { ...item, qty: item.qty + amount } : item).filter((item) => item.qty > 0));
  };

  const copyNumber = async () => {
    try { await navigator.clipboard.writeText(ACCOUNT_NUMBER); setCopied(true); setTimeout(() => setCopied(false), 2000); }
    catch { alert(`Account number: ${ACCOUNT_NUMBER}`); }
  };

  const whatsappOrder = () => {
    if (!cart.length) return;
    const items = cart.map((item) => `• ${item.name} x${item.qty} — ${naira(item.price * item.qty)}`).join("\n");
    const customerInfo = `\n\nCustomer details:\nName: ${customer.name || "Not provided"}\nPhone: ${customer.phone || "Not provided"}\nAddress: ${customer.address || "Not provided"}`;
    const message = `Hello Dream & Drift! I want to order:\n\n${items}\n\nItems total: ${naira(cartTotal)}\nDelivery: ${naira(delivery)}\nTOTAL: ${naira(grandTotal)}${customerInfo}`;
    window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`, "_blank");
  };

  return (
    <div className="app">
      <style>{`
        *{box-sizing:border-box}body{margin:0;background:#fff5f8;font-family:Arial,sans-serif;color:#333}button,input,textarea{font:inherit}.app{min-height:100vh;background:#fff5f8}
        .header{position:sticky;top:0;z-index:20;background:#fff;padding:14px 16px;display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #f5d0fe}
        .brand{font-size:22px;font-weight:900;margin:0;background:linear-gradient(90deg,#ff1493,#9333ea);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.tagline{margin:2px 0 0;font-size:10px;letter-spacing:3px;font-weight:800;color:#a855f7}
        .cart-button{border:0;color:#fff;font-weight:900;font-size:13px;padding:10px 17px;border-radius:30px;background:linear-gradient(90deg,#ff1493,#9333ea);cursor:pointer}
        .categories{position:sticky;top:75px;z-index:15;display:flex;gap:8px;overflow-x:auto;padding:12px;background:#fff;border-bottom:1px solid #f5d0fe}.category{flex:0 0 auto;padding:9px 16px;border-radius:22px;border:1px solid #f5d0fe;background:#fff;color:#a855f7;font-weight:900;font-size:12px;cursor:pointer}.category.active{background:#000;border-color:#000;color:#fff}
        .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:12px;max-width:1100px;margin:0 auto}.card{background:#fff;border:1px solid #ffe4e6;border-radius:18px;overflow:hidden;box-shadow:0 2px 8px rgba(147,51,234,.05)}.image-box{height:190px;background:#fff;display:flex;align-items:center;justify-content:center;overflow:hidden}.image-box img{width:100%;height:100%;object-fit:contain;padding:8px}.card-body{padding:12px;text-align:center}.name{font-size:12px;font-weight:800;line-height:1.3;min-height:32px;margin:0 0 7px}.price{font-size:15px;font-weight:900;color:#9333ea;margin:0 0 10px}.order{width:100%;border:0;color:#fff;padding:11px 8px;border-radius:22px;background:linear-gradient(90deg,#ff1493,#9333ea);font-weight:900;font-size:11px;cursor:pointer}
        .overlay{position:fixed;inset:0;z-index:100;background:rgba(0,0,0,.65);display:flex;align-items:flex-end;justify-content:center;padding:10px}.panel{width:100%;max-width:480px;max-height:92vh;overflow-y:auto;background:#fff;border-radius:24px 24px 16px 16px;padding:18px}.panel-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.panel h2{margin:0;font-size:20px}.close{border:0;background:#f3f4f6;border-radius:50%;width:36px;height:36px;cursor:pointer;font-size:18px}.cart-row{display:flex;gap:10px;align-items:center;padding:12px 0;border-bottom:1px solid #eee}.thumb{width:62px;height:62px;object-fit:contain;border-radius:10px;background:#fafafa}.cart-info{flex:1;min-width:0}.cart-name{font-size:12px;font-weight:800;margin:0 0 4px}.cart-price{color:#9333ea;font-weight:900;font-size:12px}.qty{display:flex;align-items:center;gap:7px}.qty button{width:28px;height:28px;border:1px solid #ddd;border-radius:8px;background:#fff;cursor:pointer;font-weight:900}.summary{margin-top:14px;padding:14px;border-radius:14px;background:#fdf4ff;border:1px solid #f5d0fe}.line{display:flex;justify-content:space-between;margin:6px 0;font-size:13px}.grand{font-size:17px;font-weight:900;color:#ff1493;border-top:1px solid #e9d5ff;padding-top:9px;margin-top:9px}.primary{width:100%;border:0;border-radius:14px;padding:14px;color:#fff;background:linear-gradient(90deg,#ff1493,#9333ea);font-weight:900;cursor:pointer;margin-top:12px}.secondary{width:100%;border:1px solid #ddd;border-radius:14px;padding:12px;background:#fff;font-weight:800;cursor:pointer;margin-top:8px}.field{width:100%;padding:12px;border:1px solid #ddd;border-radius:11px;margin-top:8px;outline:none}.bank{margin-top:14px;border:2px solid #ff1493;border-radius:16px;padding:14px}.bank-number{font-size:22px;font-weight:900;margin:5px 0}.copy{border:0;background:#111;color:#fff;border-radius:18px;padding:8px 13px;font-size:11px;font-weight:900;cursor:pointer}.note{font-size:11px;color:#777;line-height:1.5}.empty{text-align:center;padding:35px 10px;color:#777}
        @media(min-width:700px){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}.image-box{height:220px}}@media(max-width:380px){.grid{gap:8px;padding:8px}.header{padding:12px 10px}.brand{font-size:19px}.tagline{font-size:8px}.cart-button{padding:9px 12px}}
      `}</style>

      <header className="header"><div><h1 className="brand">DREAM & DRIFT</h1><p className="tagline">HAIR AND ACCESSORIES • 36 PRODUCTS</p></div><button className="cart-button" onClick={() => setShowCart(true)}>CART ({cartCount})</button></header>
      <nav className="categories">{categories.map((category) => <button key={category} className={`category ${activeCat === category ? "active" : ""}`} onClick={() => setActiveCat(category)}>{category}</button>)}</nav>

      <main className="grid">{filtered.map((product) => <article className="card" key={product.id}><div className="image-box"><img src={product.img} alt={product.name} loading="lazy" onError={(e) => { e.currentTarget.style.opacity = "0.25"; }} /></div><div className="card-body"><p className="name">{product.name}</p><p className="price">{naira(product.price)}</p><button className="order" onClick={() => addToCart(product)}>ORDER NOW</button></div></article>)}</main>

      {showCart && <div className="overlay" onClick={(e) => e.target === e.currentTarget && setShowCart(false)}><div className="panel"><div className="panel-head"><h2>Your Cart ({cartCount})</h2><button className="close" onClick={() => setShowCart(false)}>×</button></div>{!cart.length ? <div className="empty">Your cart is empty.</div> : <>{cart.map((item) => <div className="cart-row" key={item.id}><img className="thumb" src={item.img} alt={item.name} /><div className="cart-info"><p className="cart-name">{item.name}</p><span className="cart-price">{naira(item.price)}</span></div><div className="qty"><button onClick={() => changeQty(item.id,-1)}>−</button><strong>{item.qty}</strong><button onClick={() => changeQty(item.id,1)}>+</button></div></div>)}<div className="summary"><div className="line"><span>Items</span><strong>{naira(cartTotal)}</strong></div><div className="line"><span>Delivery</span><strong>{naira(delivery)}</strong></div><div className="line grand"><span>Total</span><strong>{naira(grandTotal)}</strong></div></div><button className="primary" onClick={() => { setShowCart(false); setShowCheckout(true); }}>CONTINUE TO ORDER</button></>}</div></div>}

      {showCheckout && <div className="overlay" onClick={(e) => e.target === e.currentTarget && setShowCheckout(false)}><div className="panel"><div className="panel-head"><h2>Complete Your Order</h2><button className="close" onClick={() => setShowCheckout(false)}>×</button></div><p className="note">Enter your details, then send the order to Dream & Drift on WhatsApp.</p><input className="field" placeholder="Your name" value={customer.name} onChange={(e) => setCustomer({...customer,name:e.target.value})}/><input className="field" placeholder="Phone number" inputMode="tel" value={customer.phone} onChange={(e) => setCustomer({...customer,phone:e.target.value})}/><textarea className="field" rows="3" placeholder="Delivery address" value={customer.address} onChange={(e) => setCustomer({...customer,address:e.target.value})}/><div className="summary"><div className="line"><span>Items</span><strong>{naira(cartTotal)}</strong></div><div className="line"><span>Delivery</span><strong>{naira(delivery)}</strong></div><div className="line grand"><span>Total</span><strong>{naira(grandTotal)}</strong></div></div><div className="bank"><strong>PAY BY TRANSFER</strong><p className="note">Moniepoint</p><div className="bank-number">{ACCOUNT_NUMBER}</div><p className="note">{ACCOUNT_NAME} • {BANK_NAME}</p><button className="copy" onClick={copyNumber}>{copied ? "COPIED!" : "COPY ACCOUNT NUMBER"}</button></div><button className="primary" onClick={whatsappOrder}>SEND ORDER ON WHATSAPP</button><p className="note">After sending the order, the seller can confirm availability, delivery details and payment.</p><button className="secondary" onClick={() => setShowCheckout(false)}>CLOSE</button></div></div>}
    </div>
  );
}
